### PR TITLE
Fix waiting for cluster roles

### PR DESCRIPTION
**Pull request by dmage**
An attempt to address https://github.com/openshift/test-infra/issues/164.

### CODE REVIEW

**Comment by dmage** [comment]
CI flake
/retest

**Comment by dmage** [comment]
```
got error on docker inspect fork/exec /bin/docker: no such file or directory
```
/retest

**Comment by dmage** [comment]
oh c'mon
/retest

**Comment by bparees** [comment]
there was some chatter on aos-devel about the merge queue being disabled due to github apis being broken.  I don't think it would cause failing tests, but fyi this may not be mergeable until that is resolved anyway.

**Comment by bparees** [comment]
(though we can also hand merge it if the tests are all passing)

**Pull request merged**
