### PR TITLE
Remove legionus as reviewer/approver

### PR DESCRIPTION
**Pull request by adambkaplan**
* Added @coreydaley as reviewer

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

@dmage ptal at why the integration test is red.

**Comment by dmage** [comment]
@adambkaplan I've already spent on them few days

**Comment by dmage** [comment]
/hold cancel

@adambkaplan stop doing this, the tests are already red and there are no additional reasons to hold this PR.

**Pull request merged**
