### PR TITLE
OCPBUGS-35335: use SelfAccessReview to obtain user info

### PR DESCRIPTION
**Pull request by flavianmissi**
This fixes cases where openshift is running with external users (and the user api is unavailable).

---

Note that the SelfAccessReview is new on k8s 1.28, and we had vendored 1.27 so I had to upgrade to the latest. 
Because of this api bump, backports will have to be made manually, bumping the openshift and k8s api corresponding to the openshift version (1.29 for 4.16, 1.28 for 4.15).

### CODE REVIEW

**Comment by flavianmissi** [comment]
so far the test failures look unrelated to the changes..
/retest

**Comment by flavianmissi** [comment]
test failures are unrelated to the changes in this PR
/retest

**Comment by xiuwang** [comment]
/label qe-approved
/label cherry-pick-approved

Launch a hypershift hosted cluster using payload image which built from this code. And configure external oidc auth for HCP cluster.
Run the failed image registry cases in [4.15-amd64-nightly-aws-rosa-hcp-capi-stage-f7](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/52916/rehearse-52916-periodic-ci-openshift-openshift-tests-private-release-4.15-amd64-nightly-aws-rosa-hcp-capi-stage-f7/1801429699298070528) , all suitable cases are passed.

**Review by dmage — APPROVED** [review]

**Pull request merged**
