### PR TITLE
Bug 2070791: Support authentication using gcp workload identity federation

### PR DESCRIPTION
**Pull request by dmage**
Vendor changes from https://github.com/openshift/docker-distribution/pull/31.

### CODE REVIEW

**Comment by xiuwang** [comment]
Installation succeed on ipi gcp &sts， and image registry working well, could pull and push image from it.
But the Upi gcp & sts failed after the sts setting, need to check more
```
06-17 16:51:53.771  Waiting for create [operation-1655455913007-5e1a0dda2da0f-6a44f026-2020fe1a]...
06-17 16:52:10.692  ..............failed.
06-17 16:52:10.692  ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1655455913007-5e1a0dda2da0f-6a44f026-2020fe1a]: errors:
06-17 16:52:10.693  - code: RESOURCE_ERROR
06-17 16:52:10.693    location: /deployments/wxjstsd-42br8-int-svc-instance/resources/wxjstsd-42br8-int-svc
06-17 16:52:10.693    message: "{\"ResourceType\":\"compute.v1.instance\",\"ResourceErrorCode\":\"403\"\
06-17 16:52:10.693      ,\"ResourceErrorMessage\":{\"code\":403,\"errors\":[{\"domain\":\"global\",\"\
06-17 16:52:10.693      message\":\"Permission denied on 'locations/us-east1-a' (or it may not exist).\"\
06-17 16:52:10.693      ,\"reason\":\"forbidden\"}],\"message\":\"Permission denied on 'locations/us-east1-a'\
06-17 16:52:10.693      \ (or it may not exist).\",\"status\":\"PERMISSION_DENIED\",\"statusMessage\"\
06-17 16:52:10.693      :\"Forbidden\",\"requestPath\":\"[https://compute.googleapis.com/compute/v1/projects/openshift-qe/zones/us-east1-a/instances\](https://compute.googleapis.com/compute/v1/projects/openshift-qe/zones/us-east1-a/instances/)"\
06-17 16:52:10.693      ,\"httpMethod\":\"POST\",\"suggestion\":\"Consider granting permissions to 1042363005003@cloudservices.gserviceaccount.com\"\
06-17 16:52:10.693      }}"
```

**Review by akhil-rane — COMMENTED** [review]
/lgtm

**Comment by akhil-rane** [comment]
> UPI on gcp & enable gcp workload identity federation installed successfully too and image registry working well, could pull and push image from it.
> And normal gcp cluster without gcp workload identity installation passed.

Perfect! thanks a lot for testing it out @xiuwang

**Comment by akhil-rane** [comment]
@dmage we might want to cherry-pick this to 4.10?

**Comment by dmage** [comment]
we need to manually bump `openshift/docker-distribution` to its `release-4.10` branch, automatic cherry-pick won't give right results

**Comment by akhil-rane** [comment]
> we need to manually bump openshift/docker-distribution to its release-4.10 branch, automatic cherry-pick won't give right results

@dmage agreed! here is the PR for the same  https://github.com/openshift/image-registry/pull/336

**Pull request merged**
