### PR TITLE
Remove remote stat from blobDescriptorService

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by bparees** [comment]
@dmage what made this code unnecessary?

**Comment by legionus** [comment]
> what made this code unnecessary?

We verify the blobs/manifests in our code. We can't do it in upstream any more since we are doing more than them. The `BlobDescriptorService`  should no longer be called for non-local blobs.

**Comment by dmage** [comment]
@bparees this code was added (as I can see) to give the upstream code knowledge about pullthrough. But later we implemented verification on our side and now it works with our pullthroughBlobStore. The upstream code isn't involved in verification anymore, thus this code can be removed.

It's a part of the long running story about untangling our code. pkg/dockerregistry/server contains a lot of code which is hard to decouple. It makes code harder to test and debug. As a visible consequence: it prevents me from doing #86. Also it complicates fixing our logging.

**Pull request merged**
