### PR TITLE
Bug 1804160: Permission denied if namespace does not exist

### PR DESCRIPTION
**Pull request by ricardomaraschini**

### CODE REVIEW

**Comment by ricardomaraschini** [comment]
@dmage This would be a different approach, detecting the error when uploading the manifest. Let me know what you think.

**Comment by dmage** [comment]
@ricardomaraschini looks good, we need a test for that

**Comment by ricardomaraschini** [comment]
> @ricardomaraschini looks good, we need a test for that

on it.

**Comment by ricardomaraschini** [comment]
@dmage ptal

**Comment by dmage** [comment]
We may eventually refactor our integration tests into e2e tests
/lgtm

**Pull request merged**
