### PR TITLE
[3.11v2] Bug 1814722: bump(*): fix err shadowing in gcs driver

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by smarterclayton** [comment]
/hold

Need to get e2e running again

**Comment by smarterclayton** [comment]
Mirrored to `quay.io/openshift/origin-test-fixes:docker-registry-gcs-eat-error-311`

**Comment by smarterclayton** [comment]
/hold cancel

This is ready from my perspective, after this went in we have dropped to seeing almost zero 500 internal server errors (and none of those had the same symptoms as before).  So there's a good chance this caught it, or another did, and we have 4 weeks of soak on this code, so I think this is as good a bump as we can do.

**Comment by dmage** [comment]
/hold

e2e-gcp is broken

**Comment by dmage** [comment]
We have a green test for this PR: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_image-registry/230/pull-ci-openshift-image-registry-release-3.11-e2e-gcp/42

/override ci/prow/e2e-gcp
/hold cancel

**Comment by dmage** [comment]
/hold

now we have problems with images

**Pull request merged**
