### PR TITLE
OCPBUGS-39108: bump docker distribution to fix purgeuploads panic

### PR DESCRIPTION
**Pull request by flavianmissi**

### CODE REVIEW

**Comment by flavianmissi** [comment]
Putting this on hold until this can be tested, https://github.com/openshift/docker-distribution/pull/45 merged, and the go.mod reference updated to the actual repo instead of my fork.

/hold

**Comment by flavianmissi** [comment]
removing the WIP but keeping it on hold because the changes to docker-distribution are yet to merge (and we still need to update this PR once they do).

/retitle OCPBUGS-39108: bump docker distribution to fix purgeuploads panic

---

@xiuwang could you add this one to your (or Wen's) to-do list? Thank you!

**Comment by flavianmissi** [comment]
Looks like `e2e-metal-ipi-ovn-ipv6` job timed out:
```
   * could not run steps: execution cancelled
  * could not run steps: step e2e-metal-ipi-ovn-ipv6 failed: "e2e-metal-ipi-ovn-ipv6" test steps failed: ["e2e-metal-ipi-ovn-ipv6" pod "e2e-metal-ipi-ovn-ipv6-baremetalds-e2e-test" failed: could not watch pod: context canceled 
```
Doesn't seem related to this changes. I'll wait with re-triggering.

**Comment by xiuwang** [comment]
@wewang58 is working on this, thank you!

**Comment by wewang58** [comment]
@flavianmissi  Finished testing, issue is fixed.

**Comment by flavianmissi** [comment]
the docker-distribution [PR](https://github.com/openshift/docker-distribution/pull/45) has merged and I have updated the `go.mod` to point to that repository instead of my own fork so this is ready for merging.

/hold cancel

**Comment by flavianmissi** [comment]
Hi @wewang58 , this one is also about the purge uploads panic. Could you also add qe-approved label at your convenience? Thanks!

**Comment by wewang58** [comment]
Yes, https://github.com/openshift/docker-distribution/pull/45 is merged
/label qe-approved

**Pull request merged**
