### PR TITLE
Introduce gosec for security checks

### PR DESCRIPTION
**Pull request by JAORMX**
gosec does static code analysis and checks for common security issues in golang codebases.
    
This PR introduces the tool, and sets it up as a test target in the Makefile.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/approve

@JAORMX please squash your commits, looks good otherwise.

**Comment by JAORMX** [comment]
@adambkaplan I squashed them. Thanks for the feedback!

**Comment by adambkaplan** [comment]
/lgtm

Thank you for the contribution! I hope you are able to just as easily add this to other OpenShift repos.

So you are aware, the state of our `verify` job is very broken - we aren't even running verify as a part of CI (which is bad). I was able to locally confirm that your code modifications make the `verify-sec` task "green." Most other repos have a working `verify` job that should confirm your code changes pass.

I'll work with my team to fix that up in a separate PR. fyi @openshift/openshift-team-developer-experience

**Pull request merged**
