### PR TITLE
Metrics for OpenShift client and HTTP handlers

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by bparees** [comment]
/hold
(for 3.11)

**Comment by miminar** [comment]
@openshift/sig-continuous-infrastructure can there be something done about the broken e2e tests?

> failed to build "172.30.74.83:5000/e2e-test-prune-images-dt99r/prune:latest" image: dial unix /var/run/docker.sock: connect: no such file or directory

**Pull request merged**
