### PR TITLE
[release-3.11] Bug 1827744: Reduce cardinality of metrics, use summary instead of histograms

### PR DESCRIPTION
**Pull request by dmage**
Backport of #138 + update from 4.x

### CODE REVIEW

**Comment by adambkaplan** [comment]
/retitle [release-3.11] Bug 1827743: Reduce cardinality of metrics, use summary instead of histograms

**Comment by adambkaplan** [comment]
/retitle [release-3.11] Bug 1827744: Reduce cardinality of metrics, use summary instead of histograms

**Comment by adambkaplan** [comment]
/hold

Spinning on `e2e-gcp`

**Comment by smarterclayton** [comment]
Override of GCP is granted for this short term fix.

**Pull request merged**
