### PR TITLE
Update hack/ and tools/ directories

### LINKED ISSUE #8: tests in tools directory are broken
```
$ go test ./tools/junitreport/pkg/parser/gotest
--- FAIL: TestFlatParse (0.00s)
    --- FAIL: TestFlatParse/failure (0.00s)
        parser_flat_test.go:374: did not produce the correct test suites from file:
                &api.TestSuites{XMLName:xml.Name{Space:"", Local:""}, Suites:[]*api.TestSuite{(*api.TestSuite)(0xc42009caa0)}}
                &api.TestSuites{XMLName:xml.Name{Space:"", Local:""}, Suites:[]*api.TestSuite{(*api.TestSuite)(0xc42009d360)}}
    --- FAIL: TestFlatParse/skip (0.00s)
        parser_flat_test.go:374: did not produce the correct test suites from file:
                &api.TestSuites{XMLName:xml.Name{Space:"", Local:""}, Suites:[]*api.TestSuite{(*api.TestSuite)(0xc42009cb40)}}
                &api.TestSuites{XMLName:xml.Name{Space:"", Local:""}, Suites:[]*api.TestSuite{(*api.TestSuite)(0xc42009d400)}}
    --- FAIL: TestFlatParse/multiple_suites (0.00s)
        parser_flat_test.go:374: did not produce the correct test suites from file:
                &api.TestSuites{XMLName:xml.Name{Space:"", Local:""}, Suites:[]*api.TestSuite{(*api.TestSuite)(0xc42009cc80), (*api.TestSuite)(0xc42009cd20)}}
                &api.TestSuites{XMLName:xml.Name{Space:"", Local:""}, Suites:[]*api.TestSuite{(*api.TestSuite)(0xc42009d540), (*api.TestSuite)(0xc42009d5e0)}}
    --- FAIL: TestFlatParse/nested (0.00s)
        parser_flat_test.go:374: did not produce the correct test suites from file:
                &api.TestSuites{XMLName:xml.Name{Space:"", Local:""}, Suites:[]*api.TestSuite{(*api.TestSuite)(0xc42009cfa0), (*api.TestSuite)(0xc42009d040), (*api.TestSuite)(0xc42009d0e0)}}
                &api.TestSuites{XMLName:xml.Name{Space:"", Local:""}, Suites:[]*api.TestSuite{(*api.TestSuite)(0xc42009d860), (*api.TestSuite)(0xc42009d900), (*api.TestSuite)(0xc42009d9a0)}}
--- FAIL: TestNestedParse (0.00s)
    --- FAIL: TestNestedParse/failure (0.00s)
        parser_nested_test.go:535: did not produce the correct test suites from file:
                 
                object.Suites[0].TestCases[0].FailureOutput.Output:
                  a: "file_test.go:11: Error message\nfile_test.go:11: Longer\nerror\nmessage.\n
                  b: "file_test.go:11: Error message\nfile_test.go:11: Longer\nerror\nmessage."
    --- FAIL: TestNestedParse/skip (0.00s)
        parser_nested_test.go:535: did not produce the correct test suites from file:
                 
                object.Suites[0].TestCases[0].SkipMessage.Message:
                  a: "file_test.go:11: Skip message\n"
                  b: "file_test.go:11: Skip message"
    --- FAIL: TestNestedParse/multiple_suites (0.00s)
        parser_nested_test.go:535: did not produce the correct test suites from file:
                 
                object:
                  a: []*api.TestSuite{(*api.TestSuite)(0xc42009dea0), (*api.TestSuite)(0xc42009d
                  b: []*api.TestSuite{(*api.TestSuite)(0xc42011cb40), (*api.TestSuite)(0xc42011c
    --- FAIL: TestNestedParse/nested (0.00s)
        parser_nested_test.go:535: did not produce the correct test suites from file:
                 
                object:
                  a: []*api.TestSuite{(*api.TestSuite)(0xc42011c1e0), (*api.TestSuite)(0xc42011c
                  b: []*api.TestSuite{(*api.TestSuite)(0xc42011ce60), (*api.TestSuite)(0xc42011c
    --- FAIL: TestNestedParse/nested_tests_with_inline_output (0.00s)
        parser_nested_test.go:535: did not produce the correct test suites from file:
                 
                object.Suites[0]:
                  a: []*api.TestCase{(*api.TestCase)(0xc420109c00), (*api.TestCase)(0xc420109c80
                  b: []*api.TestCase{(*api.TestCase)(0xc42014a580), (*api.TestCase)(0xc42014a600
    --- FAIL: TestNestedParse/multi-suite_nested_output_with_coverage (0.00s)
        parser_nested_test.go:535: did not produce the correct test suites from file:
                 
                object.Suites[0]:
                  a: []*api.TestCase{(*api.TestCase)(0xc420109e00), (*api.TestCase)(0xc420109e80
                  b: []*api.TestCase{(*api.TestCase)(0xc42014a880), (*api.TestCase)(0xc42014a900
FAIL
FAIL    github.com/openshift/image-registry/tools/junitreport/pkg/parser/gotest 0.004s
```

### PR DESCRIPTION
**Pull request by dmage**
Closes #8.

### CODE REVIEW

**Comment by bparees** [comment]
is this just a refresh from origin? (along w/ cleaning up some extraneous files)

**Comment by dmage** [comment]
it's just `tools/hack/golang/update $REPO_DIR github.com/openshift/image-registry` from https://github.com/openshift/release/tree/master/tools/hack/golang

**Comment by dmage** [comment]
New scripts use `go test -json`, which is introduced in go v1.10. Tests should be fixed by https://github.com/openshift/release/pull/1139.

**Comment by dmage** [comment]
@smarterclayton do you know why `clusterroles.rbac.authorization.k8s.io "admin"` has disappeared from our CI cluster?

**Comment by bparees** [comment]
@smarterclayton is on PTO this week so /cc @stevekuznetsov

**Comment by openshift-docker** [comment]
Maybe I forgot to run reconcile after upgrading.  File a bug with the auth
team.




On Aug 6, 2018, at 8:07 AM, Ben Parees <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> is on PTO this week so
/cc @stevekuznetsov <https://github.com/stevekuznetsov>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/image-registry/pull/117#issuecomment-410720200>,
or mute the thread

**Comment by dmage** [comment]
@stevekuznetsov I don't know yet, we are blocked by another test now and can't merge the fix.

**Pull request merged**
