### PR TITLE
[3.9] Allow DELETE for incomplete uploads

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by bparees** [comment]
We need to add CI coverage for the 3.9 branch

**Comment by dmage** [comment]
https://github.com/openshift/release/pull/2698

**Comment by bparees** [comment]
@dmage given the state of our CI and the relatively simple nature of this change, i'm comfortable merging it if you are.

**Comment by dmage** [comment]
Yes, at least we know that unit tests are green, so I'm ok.
/hold cancel

**Pull request merged**
