### PR TITLE
TRT-1092: Revert "Merge pull request #370 from flavianmissi/bump-docker-distrib…

### PR DESCRIPTION
**Pull request by neisw**
Reverts # [image-registry/pull/370](https://github.com/openshift/image-registry/pull/370); tracked by [TRT-1092](https://issues.redhat.com/browse/TRT-1092)

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

Observing CI Hypershift failures in [4.14.0-0.ci-2023-06-16-074926](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.ci/release/4.14.0-0.ci-2023-06-16-074926)

### CODE REVIEW

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn

**Comment by stbenjam** [comment]
Tagging to merge to get payloads green again.  We think the evidence is pretty high this is what broke hypershift.

We can't trigger the payload job, but if for some reason we're wrong will unrevert this quickly.

**Comment by jmguzik** [comment]
(just testing sth)

/payload-job periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn

**Comment by jmguzik** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn

**Comment by jmguzik** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn

**Comment by jmguzik** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn

**Pull request merged**
