### PR TITLE
Revert "[OCPNODE-1258] Support both icsp and idms"

### PR DESCRIPTION
**Pull request by stbenjam**
Reverts openshift/image-registry#346; tracked by [TRT-1165](https://issues.redhat.com//browse/TRT-1165)

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

Metal IPv6 jobs are failing to pull images, it seems to be ignoring the ICSP set in the cluster (see below logs).

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR  to confirm the fix has corrected the problem:

    `/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6`

```
  Jul 24 18:08:27.139: INFO: At 2023-07-24 18:07:44 +0000 UTC - event for idling-echo-pknd8-1-644fk: {kubelet worker-1.ostest.test.metalkube.org} Failed: Failed to pull image "image-registry.openshift-image-registry.svc:5000/openshift/tools:latest": rpc error: code = Unknown desc = reading manifest latest in image-registry.openshift-image-registry.svc:5000/openshift/tools: unknown: unable to pull manifest from quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5e867a5c890c44b5571fab14e5cf377b016a3d1308544770644a88b1edad40fb: Get "https://quay.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

```
---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  creationTimestamp: "2023-07-24T16:08:09Z"
  generation: 1
  managedFields:
  - apiVersion: operator.openshift.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:repositoryDigestMirrors: {}
    manager: cluster-bootstrap
    operation: Update
    time: "2023-07-24T16:08:09Z"
  name: image-policy
  resourceVersion: "1621"
  uid: 74a7fcca-6c40-4397-aa44-40c6636e35bc
spec:
  repositoryDigestMirrors:
  - mirrors:
    - virthost.ostest.test.metalkube.org:5000/localimages/local-release-image
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - virthost.ostest.test.metalkube.org:5000/localimages/local-release-image
    source: registry.build05.ci.openshift.org/ci-op-vjz5wv9h/release
```

CC: @QiWang19, @dmage

### CODE REVIEW

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6

**Comment by stbenjam** [comment]
Thanks @deepsm007.  TRT will merge this revert pending confirmation from https://github.com/openshift/image-registry/pull/374#issuecomment-1648512446

**Comment by derekhiggins** [comment]
IPv6 payload job has passed https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-image-registry-374-nightly-4.14-e2e-metal-ipi-ovn-ipv6/1683565064113623040

**Comment by stbenjam** [comment]
/override ci/prow/e2e-aws-image-registry

Unrelated failure

**Pull request merged**
