### PR TITLE
Use kubernetes-1.12.6

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by bparees** [comment]
seems like we're safer staying on the level that origin is using (especially in case of carries), what's the motivation to move off it?

**Comment by dmage** [comment]
It seems that [other components](https://github.com/openshift/cluster-openshift-apiserver-operator/blob/master/glide.yaml) use the upstream branches.

**Comment by bparees** [comment]
/lgtm 

but we should get back on the origin fork when we can.

**Comment by bparees** [comment]
> It seems that other components use the upstream branches.

it's not the most critical thing, but it seems like we'd benefit from using a common level where possible (ie where we don't have unique carries)

**Pull request merged**
