### PR TITLE
Bug 1814720: fix err shadowing in gcs driver

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by adambkaplan** [comment]
@dmage do we still want to merge this?

**Comment by dmage** [comment]
@adambkaplan yes, we may wait a bit until #230 is tested.

**Comment by adambkaplan** [comment]
/hold

Until we get word on how #230 testing goes

**Comment by dmage** [comment]
Oh... We've already merged it somewhere else.

**Pull request closed without merging**
