### PR TITLE
create container.yaml for odcs multi-arch build

### PR DESCRIPTION
**Pull request by jeffdyoung**
create container.yaml for odcs multi-arch build
@dorzel @adammhaile Please review.

### CODE REVIEW

**Comment by adammhaile** [comment]
+1

**Comment by bparees** [comment]
aren't we trying to move away from rpm based builds and towards multistage builds that just directly build the go code?

@smarterclayton

**Comment by dorzel** [comment]
+1

**Comment by bparees** [comment]
/lgtm

but i'd like to revisit how we're building this image in the future so we don't use rpms

**Comment by dmage** [comment]
/hold
CI needs to be fixed.

**Comment by dmage** [comment]
https://github.com/openshift/release/issues/1812

**Comment by jeffdyoung** [comment]
Dropping this. We won't be doing odcs builds in the near future. Thanks!

**Pull request closed without merging**
