### PR TITLE
Bug 1740391: Update make verify for release-4.1

### PR DESCRIPTION
**Pull request by coreydaley**
- Remove .travis.yml
- update make verify to remove gometalinter
- fix go vet to run on newer version

### CODE REVIEW

**Comment by coreydaley** [comment]
I was unable to cherry-pick this from another pr due to a conflict.

**Comment by bparees** [comment]
@stevekuznetsov i'm surprised this BZ is considered "valid" when the 4.1.z BZ doesn't link to a verified 4.2 BZ?

@coreydaley it'll help the patch manager if you link to the master PR anyway, since you couldn't do a direct cherry-pick.

**Comment by coreydaley** [comment]
master pull request for this backport: https://github.com/openshift/image-registry/pull/187

**Comment by coreydaley** [comment]
@crawford I think you are the patch manager.  Could you please give this the ok to merge into release-4.1?
Let me know if you have any questions

**Comment by bparees** [comment]
You don't need to ping the patch manager, they review all backport PRs
every Monday and Tuesday and should either apply the label or tell you why
they will not/ask you for details as needed.


Ben Parees | OpenShift

**Comment by coreydaley** [comment]
@bparees ok, thanks

**Comment by stevekuznetsov** [comment]
@bparees the release managers weren't confident they wanted to implement that policy yet so the current logic is - IF you link to another bug, it must be valid and have been resolved.

**Comment by derekwaynecarr** [comment]
the PR that merged in master linked against a BZ that targeted 4.1.z rather than cloning the BZ into the present development stream and using the linked BZ for the 4.1.z release.

**Comment by bparees** [comment]
> the PR that merged in master linked against a BZ that targeted 4.1.z rather than cloning the BZ into the present development stream and using the linked BZ for the 4.1.z release.

@derekwaynecarr This message is unclear to me (and probably to @coreydaley).  Does this message mean you are rejecting approval because something needs to be done?  As this process is very new for most PR authors, we need to be explicit if they need to take additional action to get their PR approved/merged.

I think you are asking for a BZ to be created against 4.2 (cloned from the 4.1.z BZ, though then the dep ordering will need to be fixed so that the 4.1.z depends on 4.2, not vice versa). Note that even if that is done, QE will not be involved in verifying that BZ because this PR affects CI logic, not product code, so the 4.2 BZ will be moved straight to verify.  @coreydaley can do the paperwork.

**Comment by coreydaley** [comment]
@derekwaynecarr @bparees ok, i think i have this all sorted out correctly and linked together correctly now.  ptal

**Comment by derekwaynecarr** [comment]
approved for 4.1.z

**Pull request merged**
