### PR TITLE
OCPBUGS-17975: Support both icsp and idms

### PR DESCRIPTION
**Pull request by QiWang19**
Reopen #346 Support both icsp and idms as https://github.com/openshift/cluster-image-registry-operator/pull/891 will fix the rbac permission issue.

### CODE REVIEW

**Comment by QiWang19** [comment]
```
E0816 11:45:20.800614       1 simplelookupicsp.go:56] unable to list IDMS config: imagedigestmirrorsets.config.openshift.io is forbidden: User "system:serviceaccount:openshift-image-registry:registry" cannot list resource "imagedigestmirrorsets" in API group "config.openshift.io" at the cluster scope
```
the above error does not appear in e2e-metal-ipi-ovn-ipv6 test: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_image-registry/375/pull-ci-openshift-image-registry-master-e2e-metal-ipi-ovn-ipv6/1692131417183490048/artifacts/e2e-metal-ipi-ovn-ipv6/gather-extra/artifacts/pods/openshift-image-registry_image-registry-7477846d57-bcj24_registry.log

**Comment by QiWang19** [comment]
@flavianmissi PTAL

**Comment by flavianmissi** [comment]
@QiWang19 is your team handling docs for this or do we want to IR docs involved? similar question regarding PX, do you have a PX contact to give the px-approved label here?

**Comment by QiWang19** [comment]
> @QiWang19 is your team handling docs for this or do we want to IR docs involved? similar question regarding PX, do you have a PX contact to give the px-approved label here?

I don't. feature freeze team add these px/qe/docs-approved by ourselves.

**Pull request merged**
