### PR TITLE
search tag events by tag before searching by age age

### PR DESCRIPTION
**Pull request by bparees**
should improve https://bugzilla.redhat.com/show_bug.cgi?id=1589994

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton @dmage @legionus ptal

**Comment by bparees** [comment]
> Would be good to have a test

isn't our entire e2e suite pretty much a test for this?  ("can we pull images")

**Comment by bparees** [comment]
```
atal: [ci-op-22r3slzk-f7020-ig-m-fw8f]: FAILED! => {"changed": true, "cmd": ["oc", "logs", "deployment/webconsole", "--tail=50", "--config=/etc/origin/master/admin.kubeconfig", "-n", "openshift-web-console"], "delta": "0:00:00.187106", "end": "2018-06-11 21:45:50.159255", "msg": "non-zero return code", "rc": 1, "start": "2018-06-11 21:45:49.972149", "stderr": "Error from server (BadRequest): container \"webconsole\" in pod \"webconsole-d66ffdbb6-wnf5s\" is waiting to start: trying and failing to pull image", "stderr_lines": ["Error from server (BadRequest): container \"webconsole\" in pod \"webconsole-d66ffdbb6-wnf5s\" is waiting to start: trying and failing to pull image"], "stdout": "", "stdout_lines": []}
...ignoring
```

@smarterclayton 

/retest

**Comment by bparees** [comment]
@legionus is your hold for 3.11?  if so, we're actually going to land this in 3.10.

**Comment by legionus** [comment]
> is your hold for 3.11?

@bparees yes.

**Pull request merged**
