### PR TITLE
IR-371: Bump docker distribution (again)

### PR DESCRIPTION
**Pull request by flavianmissi**
This is the exact change that fixes STS: https://github.com/flavianmissi/docker-distribution/commit/bb88bf20d6a588b25639074e9f646f89532758e6#diff-42ab115e8f2c28fa837e174c081ffe3542e13f5fbd58271f06b179c1123c7905L545-L547
And it's the only difference between https://github.com/openshift/image-registry/pull/370 and this PR

### CODE REVIEW

**Comment by flavianmissi** [comment]
Failure is unrelated:
```
{"level":"error","ts":"2023-06-19T14:07:17Z","msg":"failed to setup shared OIDC provider","error":"failed to create OIDC provider: LimitExceeded: Cannot exceed quota for OpenIdConnectProvidersPerAccount: 100\n\tstatus code: 409, request id: 35f4cea4-9e52-49a3-be5e-02ba89bfc26c","stacktrace":"github.com/openshift/hypershift/test/e2e.TestMain\n\t/go/src/github.com/openshift/hypershift/test/e2e/e2e_test.go:121\nmain.main\n\t_testmain.go:69\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:250"}
```
/retest

**Comment by flavianmissi** [comment]
I have merged the changes to openshift/docker-distribution master and have updated the module references here, so this is ready to go 🌮 
/assign @dmage 

This PR does not have user facing changes.
/label px-approved
/label docs-approved

**Comment by flavianmissi** [comment]
test failures look unrelated.
/retest

**Comment by flavianmissi** [comment]
putting this on hold so we can merge it together with https://github.com/openshift/cluster-image-registry-operator/pull/857
/hold

**Comment by flavianmissi** [comment]
we are close
/retest

**Comment by xiuwang** [comment]
Test with https://github.com/openshift/cluster-image-registry-operator/pull/857 and cco 523 pr.
Could set registry to use the workload identity token manually and aws sts/ hypershift installation succeed.

**Pull request merged**
