### PR TITLE
IR-401: pkg/dockerregistry/server/configuration: remove OPENSHIFT_DEFAULT_REGISTRY support

### PR DESCRIPTION
**Pull request by flavianmissi**

### CODE REVIEW

**Comment by flavianmissi** [comment]
failure seems unrelated

**Comment by flavianmissi** [comment]
e2e failure seems unrelated
/retest

**Comment by flavianmissi** [comment]
@xiuwang or @wewang58 could either of you help with qe approval?
This removes support for the legacy OPENSHIFT_DEFAULT_REGISTRY env var, which used to be a way to customise the registry address. 
Thank you!

**Comment by sferich888** [comment]
What feature is this connected to?

**Comment by flavianmissi** [comment]
> What feature is this connected to?

Hi @sferich888,
This first came up when solving OCPBUGS-17674 (see https://github.com/openshift/openshift-apiserver/pull/387). This is cleanup work and it's not currently part of any feature.

**Pull request merged**
