### PR TITLE
DO NOT MERGE - Testing e2e job

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
@stevekuznetsov looks like prow jobs don't propagate the env of the test container (i specified three env vars on the prow job container and none of them were merged).

**Comment by kargakis** [comment]
Seems all got propagated in the ci-operator container. Would you expect them elsewhere?
<details>

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: restricted
    prow.k8s.io/job: pull-ci-image-registry-e2e
  creationTimestamp: 2018-05-11T04:51:51Z
  labels:
    created-by-prow: "true"
    event-GUID: 033ef6c0-54d7-11e8-9cbf-307b5a585528
    prow.k8s.io/id: 03a9039d-54d7-11e8-b6e6-0a58ac100377
    prow.k8s.io/type: presubmit
  name: 03a9039d-54d7-11e8-b6e6-0a58ac100377
  namespace: ci
  resourceVersion: "11840381"
  selfLink: /api/v1/namespaces/ci/pods/03a9039d-54d7-11e8-b6e6-0a58ac100377
  uid: 053d6e86-54d7-11e8-a94a-42010a8e0003
spec:
  containers:
  - command:
    - /tools/entrypoint
    env:
    - name: JOB_NAME_SAFE
      value: e2e-gcp
    - name: CLUSTER_TYPE
      value: gcp
    - name: CONFIG_SPEC
      valueFrom:
        configMapKeyRef:
          key: config.json
          name: ci-operator-image-registry
    - name: RPM_REPO_BASEURL_REF
      value: https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/.latest-rpms
    - name: ARTIFACTS
      value: /logs/artifacts
    - name: BUILD_ID
      value: "994802242202636288"
    - name: BUILD_NUMBER
      value: "994802242202636288"
    - name: ENTRYPOINT_OPTIONS
      value: '{"args":["/bin/bash","-c","#!/bin/bash\nset -e\nexport RPM_REPO=\"$(
        curl -q \"${RPM_REPO_BASEURL_REF}\" 2\u003e/dev/null)\"\nci-operator \\\n  --delete-when-idle=10m
        --dry-run=false \\\n  --secret-dir=/usr/local/e2e-gcp-cluster-profile --template=/usr/local/e2e-gcp
        \\\n  --target=e2e-gcp\n"],"timeout":7200000000000,"grace_period":15000000000,"process_log":"/logs/process-log.txt","marker_file":"/logs/marker-file.txt"}'
    - name: GOPATH
      value: /home/prow/go
    - name: JOB_NAME
      value: pull-ci-image-registry-e2e
    - name: JOB_SPEC
      value: '{"type":"presubmit","job":"pull-ci-image-registry-e2e","buildid":"994802242202636288","prowjobid":"03a9039d-54d7-11e8-b6e6-0a58ac100377","refs":{"org":"openshift","repo":"image-registry","base_ref":"master","base_sha":"d5a32198ec0f0477741e7e09166a1e491982d4c8","pulls":[{"number":82,"author":"smarterclayton","sha":"fb50ba6b3ac0f223530c5ecf453914a27e09c7c9"}]}}'
    - name: JOB_TYPE
      value: presubmit
    - name: PROW_JOB_ID
      value: 03a9039d-54d7-11e8-b6e6-0a58ac100377
    - name: PULL_BASE_REF
      value: master
    - name: PULL_BASE_SHA
      value: d5a32198ec0f0477741e7e09166a1e491982d4c8
    - name: PULL_NUMBER
      value: "82"
    - name: PULL_PULL_SHA
      value: fb50ba6b3ac0f223530c5ecf453914a27e09c7c9
    - name: PULL_REFS
      value: master:d5a32198ec0f0477741e7e09166a1e491982d4c8,82:fb50ba6b3ac0f223530c5ecf453914a27e09c7c9
    - name: REPO_NAME
      value: image-registry
    - name: REPO_OWNER
      value: openshift
    image: docker-registry.default.svc:5000/ci/ci-operator:latest
    imagePullPolicy: Always
    name: test
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000130000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /usr/local/e2e-gcp
      name: job-definition
      subPath: cluster-launch-e2e.yaml
    - mountPath: /usr/local/e2e-gcp-cluster-profile
      name: cluster-profile
    - mountPath: /logs
      name: logs
    - mountPath: /home/prow/go
      name: code
    - mountPath: /tools
      name: tools
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-696vw
      readOnly: true
    workingDir: /home/prow/go/src/github.com/openshift/image-registry
```
</details>

**Comment by stevekuznetsov** [comment]
It will be set on the `test` container

**Comment by smarterclayton** [comment]
!!!!!!!!!!!!!!!!!!!!!1!!!

Green https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_image-registry/82/pull-ci-image-registry-e2e/996548247319220224/

**Comment by smarterclayton** [comment]
/test e2e

I think for artifact gathering we could do a simple controller that watches for namespaces owned by the ci-operator, looks at pods that have annotations, and then does an oc rsync from that pod into the local space and then uploads those to GCS.

**Comment by smarterclayton** [comment]
Units have artifacts.  Working on e2e artifacts.

**Comment by smarterclayton** [comment]
All tests are green, jobs are cut over

**Pull request closed without merging**
