### PR TITLE
Remove legacy path from imageStream.HasBlob

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by bparees** [comment]
i guess this is one way to figure out if the api is working or not..... :)

**Comment by dmage** [comment]
Oh, it seems we are going to finally drop support of `image.openshift.io/manifestBlobStored`!

**Comment by legionus** [comment]
awesome

**Comment by legionus** [comment]
> aws_vpc.new_vpc: Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.

awesome

**Comment by legionus** [comment]
> aws_iam_role.master_role: Error creating IAM Role ci-op-c0750z1r-6ec77-master-role: EntityAlreadyExists: Role with name ci-op-c0750z1r-6ec77-master-role already exists.

awesome

**Pull request merged**
