### PR TITLE
Upgrade Registry compiler and dependencies

### PR DESCRIPTION
**Pull request by legionus**

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

fyi I've created a `master-4.2` branch to land this work. You may keep using this PR to iterate on any additional fixes you discover.

**Comment by legionus** [comment]
@adambkaplan I cannot use `master-4.2` because it's too old. You can't just cherry-pick commits. Rebase must be redone from scratch if the `master-4.2` is not the same as `master` because I am changing dependencies of code.

**Pull request merged**
